# Generated by Django 3.1.1 on 2022-02-04 20:09

import content_app.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(default='Articles/default.jpg', upload_to=content_app.models.upload_to, verbose_name='Image')),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=250, unique_for_date='published')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContentConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(default='playlist/default.jpg', upload_to=content_app.models.upload_to, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(default='pod-cast_cover/default.jpg', upload_to=content_app.models.upload_to, verbose_name='Image')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcast_Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('thumbnail', models.ImageField(default='pod-cast_pod/default.jpg', upload_to=content_app.models.upload_to, verbose_name='Image')),
                ('description', models.TextField()),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Article_Read',
            fields=[
                ('contentconsumption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content_app.contentconsumption')),
            ],
            bases=('content_app.contentconsumption',),
        ),
        migrations.CreateModel(
            name='Pod_Stream',
            fields=[
                ('contentconsumption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content_app.contentconsumption')),
            ],
            bases=('content_app.contentconsumption',),
        ),
        migrations.CreateModel(
            name='Song_Stream',
            fields=[
                ('contentconsumption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content_app.contentconsumption')),
            ],
            bases=('content_app.contentconsumption',),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('song_file', models.FileField(upload_to=content_app.models.upload_to, verbose_name='Song')),
                ('image', models.ImageField(default='cover-arts/default.jpg', upload_to=content_app.models.upload_to, verbose_name='Image')),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=250, unique_for_date='published')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('artist', models.CharField(max_length=250)),
                ('genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='content_app.genre')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
