# Generated by Django 3.1.1 on 2022-02-04 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcast',
            name='episodes',
            field=models.ManyToManyField(to='content_app.Podcast_Episode'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='content_app.Song'),
        ),
        migrations.AddField(
            model_name='contentconsumption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='content_app.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song_stream',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_app.song'),
        ),
        migrations.AddField(
            model_name='pod_stream',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_app.podcast_episode'),
        ),
        migrations.AddField(
            model_name='article_read',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_app.article'),
        ),
    ]
