# Generated by Django 3.1.1 on 2022-02-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0002_auto_20220204_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default='Single', max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='song_type',
            field=models.CharField(choices=[('song', 'Song'), ('mixtape', 'Mix')], default='song', max_length=10),
        ),
    ]
