# Generated by Django 3.1.1 on 2022-03-05 09:30

import content_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_app', '0005_auto_20220223_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_artist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Album', max_length=255, verbose_name='Album Title')),
                ('song_file', models.FileField(upload_to=content_app.models.upload_to, verbose_name='Song')),
                ('image', models.ImageField(default='cover-arts/default.jpg', upload_to=content_app.models.upload_to, verbose_name='Image')),
                ('description', models.TextField()),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('artist', models.CharField(max_length=250)),
                ('genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='content_app.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_artist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['-published'],
            },
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=b'N', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='album', to='content_app.album'),
        ),
    ]
