# Generated by Django 3.1.1 on 2022-03-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0006_auto_20220305_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='song_file',
        ),
    ]
